CREATE SEQUENCE IF NOT EXISTS roles_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE roles
(
    id    BIGINT NOT NULL,
    title VARCHAR(50),
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

ALTER TABLE users
    ADD role_id BIGINT;

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_ROLE FOREIGN KEY (role_id) REFERENCES roles (id);